language: python
python:
  - 3.5
services:
  - docker
before_install:
  - docker --version
env:
  global:
  - QGIS_TEST_VERSION=latest
install:
  - docker build --build-arg QGIS_TEST_VERSION=${QGIS_TEST_VERSION} .
script:
  - bash /usr/src/run-docker-tests.sh
